# Generated by Django 4.0.4 on 2022-11-27 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id_atencion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('id_interconsulta', models.OneToOneField(blank=True, db_column='id_interconsulta', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.atencion')),
            ],
            options={
                'verbose_name_plural': 'Atenciones',
                'db_table': 'atencion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('id_ciudad', models.ForeignKey(db_column='id_ciudad', on_delete=django.db.models.deletion.CASCADE, to='core.ciudad')),
            ],
            options={
                'verbose_name_plural': 'Comunas',
                'db_table': 'comuna',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleUnidad',
            fields=[
                ('id_detalle_unidad', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Detalle unidades',
                'db_table': 'detalle_unidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadPabellon',
            fields=[
                ('id_disponibilidad_pabellon', models.BigAutoField(primary_key=True, serialize=False)),
                ('disponible', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Disponibilidad pabellones',
                'db_table': 'disponibilidad_pabellon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('atencion', models.CharField(max_length=50)),
                ('riesgo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_atencion', models.ForeignKey(db_column='id_atencion', on_delete=django.db.models.deletion.CASCADE, to='core.atencion')),
            ],
            options={
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField(unique=True)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=1)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=2000)),
                ('direccion', models.CharField(max_length=100)),
                ('administrador', models.CharField(max_length=1)),
                ('habilitado', models.CharField(max_length=1)),
                ('id_cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.CASCADE, to='core.cargo')),
                ('id_comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
                ('id_jefe', models.ForeignKey(blank=True, db_column='id_jefe', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
            ],
            options={
                'verbose_name_plural': 'Medicos',
                'db_table': 'medico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.BigAutoField(primary_key=True, serialize=False)),
                ('hora_ini', models.DateField()),
                ('hora_fin', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Modulos',
                'db_table': 'modulo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pabellon',
            fields=[
                ('id_pabellon', models.BigAutoField(primary_key=True, serialize=False)),
                ('piso', models.IntegerField()),
                ('numeracion', models.IntegerField()),
                ('habilitado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Pabellones',
                'db_table': 'pabellon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=1)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProgramacionCirugia',
            fields=[
                ('id_reserva_cirugia', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('notificado', models.CharField(max_length=1)),
                ('id_detalle_unidad', models.ForeignKey(db_column='id_detalle_unidad', on_delete=django.db.models.deletion.CASCADE, to='core.detalleunidad')),
                ('id_evaluacion', models.ForeignKey(db_column='id_evaluacion', on_delete=django.db.models.deletion.CASCADE, related_name='id_evaluacion_related', to='core.evaluacion')),
                ('id_medico', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='core.evaluacion')),
            ],
            options={
                'verbose_name_plural': 'Programacion de cirugias',
                'db_table': 'programacion_cirugia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_recurso', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad_actual', models.IntegerField()),
                ('cantidad_maxima', models.IntegerField()),
                ('cantidad_peligro', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Recursos',
                'db_table': 'recurso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Regiones',
                'db_table': 'region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReservaPabellon',
            fields=[
                ('id_reserva', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_disponibilidad_pabellon', models.ForeignKey(db_column='id_disponibilidad_pabellon', on_delete=django.db.models.deletion.CASCADE, to='core.disponibilidadpabellon')),
                ('id_reserva_cirugia', models.OneToOneField(db_column='id_reserva_cirugia', on_delete=django.db.models.deletion.CASCADE, to='core.programacioncirugia')),
            ],
            options={
                'verbose_name_plural': 'Reserva pabellones',
                'db_table': 'reserva_pabellon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id_unidad', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidad',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
        migrations.AddField(
            model_name='disponibilidadpabellon',
            name='id_modulo',
            field=models.ForeignKey(db_column='id_modulo', on_delete=django.db.models.deletion.CASCADE, to='core.modulo'),
        ),
        migrations.AddField(
            model_name='disponibilidadpabellon',
            name='id_pabellon',
            field=models.ForeignKey(db_column='id_pabellon', on_delete=django.db.models.deletion.CASCADE, to='core.pabellon'),
        ),
        migrations.AddField(
            model_name='detalleunidad',
            name='id_medico',
            field=models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.CASCADE, to='core.medico'),
        ),
        migrations.AddField(
            model_name='detalleunidad',
            name='id_unidad',
            field=models.ForeignKey(db_column='id_unidad', on_delete=django.db.models.deletion.CASCADE, to='core.unidad'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_region',
            field=models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id_cirugia', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_reserva_cirugia', models.OneToOneField(db_column='id_reserva_cirugia', on_delete=django.db.models.deletion.CASCADE, to='core.programacioncirugia')),
            ],
            options={
                'verbose_name_plural': 'Cirugias',
                'db_table': 'cirugia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BitacoraCirugia',
            fields=[
                ('id_bitacora_cirugia', models.BigAutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=3000)),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('id_cirugia', models.ForeignKey(db_column='id_cirugia', on_delete=django.db.models.deletion.CASCADE, to='core.cirugia')),
            ],
            options={
                'verbose_name_plural': 'Bitacoras de cirugia',
                'db_table': 'bitacora_cirugia',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='atencion',
            name='id_medico',
            field=models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.CASCADE, to='core.medico'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
        migrations.CreateModel(
            name='ReservaRecurso',
            fields=[
                ('id_reserva_recurso', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
                ('id_recurso', models.OneToOneField(db_column='id_recurso', on_delete=django.db.models.deletion.CASCADE, to='core.recurso')),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, to='core.reservapabellon')),
            ],
            options={
                'verbose_name_plural': 'Reserva recursos',
                'db_table': 'reserva_recurso',
                'managed': True,
                'unique_together': {('id_recurso', 'id_reserva')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('id_evaluacion', 'id_paciente')},
        ),
    ]
