# Generated by Django 4.0.4 on 2022-11-28 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='id_comuna',
        ),
        migrations.AddField(
            model_name='medico',
            name='id_ciudad',
            field=models.ForeignKey(db_column='id_ciudad', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ciudad'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
    ]
