# Generated by Django 4.1.7 on 2023-06-11 21:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_medico_id_comuna_medico_id_ciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(choices=[('ingin', 'Ingeniería en Informática'), ('ingred', 'Ingeniería en Conectividad y Redes'), ('publ', 'Publicidad'), ('digt', 'Animación Digital'), ('ingmark', 'Ingeniería en Marketing Digital'), ('audi', 'Auditoría')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id_escuela', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_escuela', models.CharField(choices=[('escinf', 'Escuela de Informática y Telecomunicaciones'), ('escomun', 'Escuela de Comunicación'), ('escadmin', 'Escuela de Administración y Negocios')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=500)),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrera')),
            ],
            options={
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
            ],
        ),
        migrations.RemoveField(
            model_name='bitacoracirugia',
            name='id_cirugia',
        ),
        migrations.RemoveField(
            model_name='cirugia',
            name='id_reserva_cirugia',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='id_region',
        ),
        migrations.RemoveField(
            model_name='detalleunidad',
            name='id_medico',
        ),
        migrations.RemoveField(
            model_name='detalleunidad',
            name='id_unidad',
        ),
        migrations.RemoveField(
            model_name='disponibilidadpabellon',
            name='id_modulo',
        ),
        migrations.RemoveField(
            model_name='disponibilidadpabellon',
            name='id_pabellon',
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='id_atencion',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='id_paciente',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='id_cargo',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='id_ciudad',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='id_jefe',
        ),
        migrations.RemoveField(
            model_name='programacioncirugia',
            name='id_detalle_unidad',
        ),
        migrations.RemoveField(
            model_name='programacioncirugia',
            name='id_evaluacion',
        ),
        migrations.RemoveField(
            model_name='programacioncirugia',
            name='id_medico',
        ),
        migrations.RemoveField(
            model_name='programacioncirugia',
            name='id_paciente',
        ),
        migrations.RemoveField(
            model_name='reservapabellon',
            name='id_disponibilidad_pabellon',
        ),
        migrations.RemoveField(
            model_name='reservapabellon',
            name='id_reserva_cirugia',
        ),
        migrations.AlterUniqueTogether(
            name='reservarecurso',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reservarecurso',
            name='id_recurso',
        ),
        migrations.RemoveField(
            model_name='reservarecurso',
            name='id_reserva',
        ),
        migrations.DeleteModel(
            name='Atencion',
        ),
        migrations.DeleteModel(
            name='BitacoraCirugia',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Cirugia',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='DetalleUnidad',
        ),
        migrations.DeleteModel(
            name='DisponibilidadPabellon',
        ),
        migrations.DeleteModel(
            name='Evaluacion',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
        migrations.DeleteModel(
            name='Pabellon',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='ProgramacionCirugia',
        ),
        migrations.DeleteModel(
            name='Recurso',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='ReservaPabellon',
        ),
        migrations.DeleteModel(
            name='ReservaRecurso',
        ),
        migrations.DeleteModel(
            name='Unidad',
        ),
        migrations.AddField(
            model_name='docente',
            name='id_escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.escuela'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiante'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacion'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.escuela'),
        ),
    ]
